coder/tailscale

net/connstats/stats.go

It should be on the responsibility of the caller to send stats or not if no activity occurred. This was making it difficult to periodically send stats because we'd need multiple tickers that would have to align.

net/connstats: always stat even if no activity occurred

---

derp/derphttp/derphttp_client.go

This was causing a leak in our CI!
This should definitely be upstreamed... it's a bug in Tailscale! https://github.com/tailscale/tailscale/pull/7483

derp/derphttp: wait for websocket connections to exit on close

---

derp/derphttp/derphttp_client.go
derp/derphttp/websocket.go
derp/derphttp/websocket_js.go

This PR modifies the `dialWebsocketFunc` to allow any DERP HTTP headers to be also passed through when dialing the websocket.
This expands upon the changes introduced in https://github.com/coder/tailscale/pull/6 to avoid errors like the one below:
```
2023-03-12 06:11:38.503 [DEBUG]	(wgengine)	<./../../../tailscale.com/derp/derphttp/derphttp_client.go:328>	(*Client).connect	derphttp.Client.Recv: connecting websocket to https://coder.some-reverse-proxy.com/derp
2023/03/12 17:11:38 websocket Dial: failed to WebSocket dial: expected handshake response status code 101 but got 403, &{Status:403 Forbidden StatusCode:403 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Cf-Ray:[7a69e1879b37ab01-SYD] Connection:[keep-alive] Content-Length:[151] Content-Type:[text/html] Date:[Sun, 12 Mar 2023 …
```

derp/derphttp: pass the headers to the websocket dial

---

derp/derphttp/derphttp_client.go
wgengine/magicsock/magicsock.go

Coder pods using the embedded relay would dial the access URL to dial DERP. This is unnecessary and led to oddities in deployments with restricted networking.
This will allow us to directly dial the DERP server, eliminating the external network path entirely.
See https://github.com/tailscale/tailscale/issues/7557

wgengine/magicsock: allow passing region dialer to derp client

---

derp/derphttp/derphttp_client.go
derp/derphttp/derphttp_test.go
derp/derphttp/websocket.go

HTTP/2 doesn't support the 'Upgrade' header, which breaks the DERP exchange.

fix: add websocket fallback when http2 is used

---

net/tlsdial/tlsdial.go

Related: https://github.com/coder/coder/issues/6640
It seems that we don't need to scare users with Let's Encrypt warning.

chore: hide Lets Encrypt cert warning

---

wgengine/netstack/netstack.go

See https://github.com/tailscale/tailscale/pull/8106

wgengine/netstack: switch to cubic congestion control

---

wgengine/netstack/netstack.go

Related: https://github.com/coder/coder/issues/7388
This PR disables TCP SACK (enabled by default) as in other experiments with MinRTO, MaxRTO tweaking didn't work. The idea is to keep this fix until the issue in gvisor is resolved. It also reverts https://github.com/coder/tailscale/pull/24.
I will follow-up with PR to coder/coder.

wgengine/netstack: disable TCP SACK

---

derp/derphttp/derphttp_client.go
net/netcheck/netcheck.go

Changes the STUN probe to still run as usual, but avoid storing the latency in the region report. This was causing Google STUN to artificially make the default region have an extremely low latency.
Also fixes HTTPS latency check to work on ForceHTTP nodes.

fix: never use STUN latency for DERP region netcheck

---

wgengine/userspace.go

Fixes deadlocks seen in https://github.com/coder/coder/issues/9018 by preventing activity from reprogramming wireguard after we've started closing the userspace engine.

Don't process activity during closing

---

derp/derp_client.go

To potentially help us debug this.

chore: add frame type to `unexpectedly large frame` error

---

net/netcheck/netcheck.go
net/netcheck/netcheck_test.go
tailcfg/derpmap.go
wgengine/magicsock/derp.go

During a customer call I realized that their client/workspace was picking a STUN-only region as the preferred region which is not good.
Related to https://github.com/coder/coder/issues/9550

fix: always avoid picking stun-only regions as preferred region

---

net/netcheck/netcheck.go
net/netcheck/netcheck_test.go
wgengine/magicsock/magicsock.go

If the DERP server requires e.g. an auth header for the identity proxy then netcheck will always fail on the HTTP latency probes.

fix: use magicsock DERPHeaders in netcheck

---

tailcfg/derpmap.go
tailcfg/tailcfg_test.go
wgengine/magicsock/magicsock.go

This is a confusing log line to customers and happens when STUN is disabled. Also avoids the constant rebinding every 20 seconds which is pointless since we're not using the UDP socket at all in these situations.

chore: avoid logging netcheck send errors if STUN is disabled

---

derp/derp_client.go
derp/derphttp/derphttp_client.go

Some more logging to hopefully get to the bottom of https://github.com/coder/coder/issues/9337

Log DERP connection logic and overlarge frame head

---

net/netcheck/netcheck.go
net/netcheck/netcheck_test.go
wgengine/magicsock/magicsock_test.go

I'm still noticing some instability and my agent isn't probing STUN regions, and therefore failing netchecks.
I've noticed a bug in our planning, introduced with my previous change.  The choice of number of probes and v4 vs v6 for the probes was being computed based on the sorted speed index, rather than the relative index of only STUN regions.  So, if the first STUN region wasn't in the top 3 by speed, it could only get a single try and/or only v6 probes.  In pathological cases, you could end up with only v6 probes and no v4 probes.

fix: plan v4/v6 STUN probing based on relative index

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

Previously, BlockEndpoints was only implemented on Coder's side in the coordination protocol and by removing STUN servers from the DERP map. This had some gaps though... local endpoints gathered from interfaces on the PC would still be gathered and could still be sent to the other peer using disco call-me-maybe packets.
This disables storing (and therefore sending) any endpoints using a runtime-controllable setting on magicsock.
The UDP socket and portmapper are still created (for now) as removing them fully did not seem trivial without causing many bugs in the process.
Updates coder/coder#10791

feat: add magicsock opt to block direct endpoints

---

wgengine/netstack/netstack.go

In my testing, this increased `coder speedtest` throughput 29 -> 85 Mbit/s from Abu Dhabi to Helsinki, up to near-identical performance with native `scp`.

feat: set large TCP buffers, SACK, and CUBIC congestion control

---

hostinfo/hostinfo.go
hostinfo/hostinfo_linux.go

Upstream: https://github.com/tailscale/tailscale/pull/11577

chore: lazily load linux device model to speed up `init()`

---

net/dnscache/dnscache.go

Upstream PR: https://github.com/tailscale/tailscale/pull/11935
Fixes flake seen here: https://github.com/coder/coder/actions/runs/8887860105/job/24403798734#step:5:376

net/dnscache: use parent context to perform lookup

---

wgengine/netstack/netstack.go

If we fail to dial `127.0.0.1:x` over TCP when forwarding traffic, try `::1` as well.
This doesn't apply to UDP connections, which don't have "connections" and we therefore can't detect failures (unless we retried every single packet, which I think is a bad idea). The majority of users are only using TCP anyways so I think it's OK.
Relates to coder/coder#12906

feat: try IPv6 when dialing IPv4 loopback

---

AUTHORS
wgengine/netstack/endpoint.go
wgengine/netstack/endpoint_test.go
wgengine/netstack/netstack.go

part of: https://github.com/coder/coder/issues/13108
should increase our throughput at various latencies:

fix: block writes from gVisor to tailscale instead of dropping

---

derp/derp_server.go

the `counter_packets_dropped_reason` metric is using incorrect labels, probably because a reason was dropped and a new one added to the end, causing the reasons between to be shifted out of alignment with their labels in the metrics.
The actual reasons are
```
const (
dropReasonUnknownDest      dropReason = iota // unknown destination pubkey
dropReasonUnknownDestOnFwd                   // unknown destination pubkey on a derp-forwarded packet
dropReasonGoneDisconnected                   // destination tailscaled disconnected before we could send
dropReasonQueueHead                          // destination queue is full, dropped packet at queue head
dropReasonQueueTail                          // destination queue is full, dropped packet at queue tail
dropReasonWriteError …
```

fix: fix dropReason metrics labels

---

tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go
wgengine/magicsock/magicsock.go

Tailscale chooses not to expose `netcheck.Report`, and instead opts to make `tailcfg.NetInfo` available via a callback, which is built using a `Report`. There's a few pieces of data in `Report` that we'd like to have for our network telemetry. 
Furthermore, `NetInfo` is not a proper subset of `Report`, so replacing it is non-trivial.
We should instead make `NetInfo` a superset of `Report`, as a means of future-proofing what we have access to from Tailscale in our network telemetry.

chore: add missing netcheck report fields to netinfo

---

wgengine/netstack/netstack.go

Fixes: https://github.com/coder/coder/issues/14712
SSH can hang for a really long time if you lose connectivity to your workspace, e.g. lose WiFi moving your laptop around, etc.  If you're running `coder ssh` it becomes just an unresponsive terminal, and you have to open a new terminal to kill the process.
This PR configures our TCP connections with gVisor so that they time out in 15-30s if you try to send data and don't get a response.  That amount of time should allow Tailscale/Wireguard to reconnect if possible, while not making the user wait around a ton of time if it's just never going to work, based on their (lack of) network connectivity.

fix: set TCPMaxRetries to 5 for reasonable timeouts on send

---

wgengine/netstack/netstack.go

relates to: https://github.com/coder/coder/issues/14715
For CoderVPN, we need Agents to operate on a separate Unique Local Address (ULA) prefix than Tailscale, so that CoderVPN and Tailscale can both run on the same computer.
This PR fixes an issue in the Tailscale netstack, where it uses the hardcoded Tailscale ULA to decide whether to forward TCP connections to localhost (127.0.0.1), rather than just checking whether the destination is an address assigned to the node.
Pretty sure this is just a bug / another case of assumptions that are true for Tailscale but not for us.  `acceptTCP()` makes a call to `removeSubnetAddress()` in a defer. This was originally conditional on `isTailscaleIP`, but the check for `addSubnetAddress()` on line 311 uses `isLocalIP()`.  Stepping thru the code, if …

fix: fix netstack to forward TCP sessions to local addresses

---

net/dns/config.go
net/dns/manager_test.go
net/tsaddr/tsaddr.go
net/tsaddr/tsaddr_test.go
wgengine/netstack/netstack.go

Relates to https://github.com/coder/coder/issues/14718
This enables the Tailscale built-in DNS nameserver (`Resolver`) to listen on the pre-determined Coder DNS address, `[fd60:627a:a42b::53]:53`. 
Note that there's currently a hardcoded check in the DNS manager that ignores the hosts on `dns.Config` unless `goos= "windows"`. This means the platform specific part of CoderVPN won't get the specific host mappings, only the address of the Tailscale nameserver. If we need to modify the hosts file on Windows, we'll need to change that (answer pending dean's return) .
For example, this `in: dns.Config` produces the following OS config, and Resolver config:
```
in: Config{
OnlyIPv6: true,
Routes: map[dnsname.FQDN][]*dnstype.Resolver{
"coder.": nil,
},
Hosts: hosts(
"agent.myws.me.coder.", …
```

chore: use coder DNS service address

---

net/dns/manager_windows.go
net/dns/nrpt_windows.go
util/winutil/winutil_windows.go

Tailscale uses the hosts file as they register the tailnet as a search domain, and they want to overcome the ~3s multicast DNS timeout that often happens on home networks when there's a query for a suffixless hostname.
We currently don't use search domains, but we'd probably want to in the future, so instead of removing the hosts file code from coder/tailscale I changed the section identifiers we use.
Also updates some registry paths to avoid conflicting with Tailscale.
Closes https://github.com/coder/coder-desktop-windows/issues/15

fix: avoid interference with Tailscale on Windows

---

wgengine/magicsock/endpoint.go

One of the conditions was flipped, and it was caught by the coder integration test suite.

fix: fix BlockEndpoint condition checks

---

control/controlbase/conn_test.go
net/dns/nm.go
net/interfaces/interfaces.go
net/netmon/netmon_linux.go
net/netmon/netmon_windows.go
net/netns/netns.go
net/netns/netns_darwin.go
net/netns/netns_darwin_test.go
net/netns/netns_windows.go
net/netns/netns_windows_test.go
net/tsaddr/tsaddr.go
tsnet/tsnet_test.go
tstest/integration/integration_test.go
wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock_test.go
wgengine/netlog/logger.go
wgengine/netstack/netstack.go
wgengine/netstack/netstack_test.go
wgengine/userspace.go
wgengine/wgcfg/nmcfg/nmcfg.go

- Changes interface detection in Tailscale to use Coder IPs (thanks @ethanndickson)
- Adds new switch to netns called SetCoderSoftIsolation
- Adds a branch to the windows socket control function to determine whether soft isolation can be used for the given socket
macOS impl to come later

fix: add soft isolation mode and windows impl
